# cloud-1: terraform provisions the box, ansible configures it.
#
#   make up     provision + configure, end to end
#   make down   destroy everything (stops the billing)

TF      := terraform -chdir=terraform
KEY     := server_key.pem
PUBKEY  := server_key.pub

# Read from group_vars rather than duplicated here, so there is one place
# that defines the site's name. Override on the command line to test.
# How long `make wait` will keep polling for SSH. Override per invocation.
SSH_WAIT ?= 300

VARS    := group_vars/webservers/vars.yml
DOMAIN  := $(shell awk '/^wordpress_domain:/ {print $$2}' $(VARS))
LE      := $(shell awk '/^wordpress_tls_letsencrypt:/ {print $$2}' $(VARS))

.PHONY: up down provision inventory dns wait configure check lint fmt

# Every stage of `up` consumes what the previous one produced: inventory
# reads terraform's output, dns and wait read inventory. `make -j` would
# otherwise be free to start them concurrently.
.NOTPARALLEL:

up: provision inventory dns wait configure

# Terraform reads the public half; ansible.cfg connects with the private
# half. Deriving one from the other keeps them in sync automatically.
$(PUBKEY): $(KEY)
	ssh-keygen -y -f $(KEY) > $(PUBKEY)

provision: $(PUBKEY)
	$(TF) init -input=false
	$(TF) apply -auto-approve

# Rewrites inventory.yaml from Terraform's output, so Ansible always targets
# the instance that actually exists rather than a stale hard-coded address.
inventory:
	@IP=$$($(TF) output -raw instance_public_ip) && \
	printf -- '---\n# Generated by `make inventory` from terraform output.\nwebservers:\n  hosts:\n    cloud1:\n      ansible_host: %s\n' "$$IP" > inventory.yaml && \
	echo "inventory.yaml -> $$IP"

# The playbook's Let's Encrypt preflight asserts that every certificate
# name resolves to ansible_host, but it only reaches that assertion after
# the whole stack is already up. On a rebuild behind a freshly allocated
# EIP, DNS still points at the old address, so `configure` deploys
# everything and then aborts - leaving the site on its self-signed
# bootstrap certificate. Checking here fails before anything is deployed.
#
# Deliberately not managed in Terraform: the domain is registered outside
# AWS, so there is no Route 53 zone to write these records into.
#
# `ahostsv4`, not `ahosts`, even though the playbook's own assertion matches
# on both families. This runs on the operator's machine, and a resolver with
# DNS64 enabled synthesises an AAAA (64:ff9b::/96) for every name that has
# only an A record - which would fail this gate on a perfectly correct zone.
# The playbook's check runs on the instance itself and stays strict, so a
# genuinely stray AAAA record is still caught before certbot is called.
dns:
ifeq ($(LE),true)
	@IP=$$($(TF) output -raw instance_public_ip) && \
	bad=0; \
	for name in $(DOMAIN) www.$(DOMAIN) pma.$(DOMAIN); do \
		got=$$(getent ahostsv4 "$$name" 2>/dev/null | awk '{print $$1}' | sort -u | paste -sd, -); \
		if [ "$$got" != "$$IP" ]; then \
			echo "DNS: $$name -> $${got:-no answer} (expected $$IP)"; \
			bad=1; \
		else \
			echo "DNS: $$name -> $$IP"; \
		fi; \
	done; \
	if [ $$bad -ne 0 ]; then \
		echo; \
		echo "ERROR: DNS does not point at this instance. Update the A records"; \
		echo "above to $$IP and wait for propagation before deploying, or set"; \
		echo "wordpress_tls_letsencrypt: false in $(VARS) to deploy without"; \
		echo "a trusted certificate. Nothing has been deployed."; \
		exit 1; \
	fi
else
	@echo "dns: skipped (wordpress_tls_letsencrypt is not true)"
endif

# Wait for the instance to accept SSH before configuring it. A freshly
# created EC2 host needs cloud-init and sshd to finish before Ansible can
# connect; without this step `make up` fails on first run.
#
# One wait_for_connection call that retries internally, rather than a shell
# loop around one-shot calls: the loop paid ~1.5s of ansible start-up on
# every attempt and could only notice the host on a 15s boundary, while
# `2>/dev/null` hid the reason for each failure - so a box that never came
# up looked frozen for a quarter of an hour. This polls every 5s, prints
# what went wrong when it gives up, and is bounded by SSH_WAIT (seconds,
# 5 minutes by default):
#   make wait SSH_WAIT=900
wait:
	@echo "Waiting up to $(SSH_WAIT)s for SSH on the new instance…"
	@ansible all -i inventory.yaml -m ansible.builtin.wait_for_connection \
		-a 'delay=0 sleep=5 timeout=$(SSH_WAIT)' || { \
		echo "ERROR: instance was not SSH-reachable within $(SSH_WAIT)s."; \
		echo "Check the key pair, security group, and instance console output."; \
		exit 1; \
	}
	@echo "Instance is reachable."

configure:
	ansible-galaxy collection install -r requirements.yml
	ansible-playbook site.yml

# Dry run. Always worth doing before touching a working box.
check:
	ansible-playbook site.yml --check --diff

# terraform/eip is a separate root module, so `$(TF) validate` - scoped to
# terraform/ by -chdir - never reaches it. Validate it explicitly.
lint:
	ansible-lint
	$(TF) fmt -check -recursive
	$(TF) init -backend=false -input=false
	$(TF) validate
	terraform -chdir=terraform/eip init -backend=false -input=false
	terraform -chdir=terraform/eip validate

fmt:
	$(TF) fmt -recursive

# Destroys the instance and its network. The Elastic IP is deliberately not
# in this module's state - it is reserved in terraform/eip so that `make up`
# comes back on the same address and the DNS records keep working. AWS bills
# an unattached address at ~$0.005/hour, so a box left down still costs a few
# dollars a month. Release it with `terraform -chdir=terraform/eip destroy`
# (and remove the prevent_destroy first) only if you are giving up the
# address for good.
down:
	$(TF) destroy -auto-approve
