# cloud-1: terraform provisions the box, ansible configures it.
#
#   make up     provision + configure, end to end
#   make down   destroy everything (stops the billing)

TF      := terraform -chdir=terraform
KEY     := server_key.pem
PUBKEY  := server_key.pub

.PHONY: up down provision inventory configure check lint fmt destroy-check

up: provision inventory configure

# Terraform reads the public half; ansible.cfg connects with the private
# half. Deriving one from the other keeps them in sync automatically.
$(PUBKEY): $(KEY)
	ssh-keygen -y -f $(KEY) > $(PUBKEY)

provision: $(PUBKEY)
	$(TF) init -input=false
	$(TF) apply -auto-approve

# Rewrites inventory.yaml from Terraform's output, so Ansible always targets
# the instance that actually exists rather than a stale hard-coded address.
inventory:
	@IP=$$($(TF) output -raw instance_public_ip) && \
	printf -- '---\n# Generated by `make inventory` from terraform output.\nwebservers:\n  hosts:\n    cloud1:\n      ansible_host: %s\n' "$$IP" > inventory.yaml && \
	echo "inventory.yaml -> $$IP"

configure:
	ansible-galaxy collection install -r requirements.yml
	ansible-playbook site.yml

# Dry run. Always worth doing before touching a working box.
check:
	ansible-playbook site.yml --check --diff

lint:
	ansible-lint
	$(TF) fmt -check -recursive
	$(TF) validate

fmt:
	$(TF) fmt -recursive

down:
	$(TF) destroy -auto-approve
